import Image from 'next/image';

export default function _Image({
  src,
  alt,
  title,
  width,
  height,
  ...props
}: {
  src: string;
  alt?: string;
  title?: string;
  width?: string;
  height?: string;
}) {
  const match = src.match(/#(\d*)_(\d*)/);
  if (match != null) {
    width ||= match[1];
    height ||= match[2];
  }
  return src.startsWith('/') ? (
    <div className='flex justify-center'>
      <Image {...props} src={src} alt={alt || src} title={title || 'generated by next/image'} width={parseInt(width || '300', 10)} height={parseInt(height || '300', 10)} objectFit="contain" />
    </div>
  ) : (
    <img {...props} src={src} alt={alt || src} title={title} width={width || ''} height={height || ''} />
  );
}